### ISSUE TITLE
Granting Aya-S the needed permissions to enter gitter channel and review PRs

### ISSUE THREAD

**Issue by Aya-S** [python-sprints/pandas-mentoring#95]
Hello Everyone, 
would be great if someone with the required privileges would Grant me the needed permissions to enter the gitter channel and review PRs.
TIA!

**Comment by datapythonista** [comment]
Added you to the organization and the gitter channel. :)

**Comment by Aya-S** [comment]
wohoo! thanks @datapythonista

**Comment by dujm** [comment]
@Aya-S  I know this issue was closed, but I should have clarified it earlier. It seems a team member (e.g. me) can not invite/authorize others to join the team because
 * There's no such option on my team page
 * The link I sent you is hidden to non-members (https://github.com/orgs/python-sprints/teams/pandas-mentoring/members)

So I guess only the team maintainer can invite people. And I see Marc has already added 13 people in the team. Thanks @datapythonista

**Comment by datapythonista** [comment]
@dujm do you have an `Add member` button in https://github.com/orgs/python-sprints/teams/pandas-mentoring/members ?

That's how I'm adding people to the team. Afaik I'm adding people as admins, so I guess you should have that button and be able to add other people too, but if that's not the case let me know and I'll check in more detail how to make the rest of the people admins.

Thanks!

**Comment by dujm** [comment]
![Screen Shot 2019-08-05 at 15 59 29](https://user-images.githubusercontent.com/30461000/62470170-2085d880-b79a-11e9-9be9-e45a39fb8c0f.png)

@datapythonista  No, I don't have this button, only the 'Leave team' button ;)

**Comment by datapythonista** [comment]
ok, don't touch the `Leave team` button. ;)

@dujm you were already an admin of the team and the repo, but I made you and few more people an admin of the whole organization. Hopefully now you're able to add people, otherwise not sure what else I can do.

**Comment by dujm** [comment]
:-D thanks @datapythonista Now I can see the 'Add a member button.  I will add people to the 'Team' and 'Gitter'

**Comment by datapythonista** [comment]
Thanks a lot @dujm. Feel free to send a message to the google group, if you think someone may be missing.
